### ISSUE TITLE
Credential Response Encryption

### ISSUE THREAD

**Issue by jonas-youniqx** [a-sit-plus/kmm-vc-library#460]
We currently try to get vck running with our PID issuer (which is [the EUDI kotlin issuer](https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer)).

We identified two main issues atm:
1. The backend expects an `alg` parameter in the credential response encryption jwk.
2. As soon as this is present the used `enc` must meet the requirements of the issuer. (In our case `A128GCM` instead of `A256GCM`)

Regarding the test setup: We use our own implementation but mainly try to reproduce the issues with the Valera app.

### Ad. 1

> alg (Algorithm), and other JWK parameters. The alg parameter MUST be present.

According to [the specs](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-10) the alg parameter must be present in the credential response encryption jwk.

We where able to achieve that by overwriting the `jsonWebKey` method in our key material.
```kotlin
override val jsonWebKey: JsonWebKey
        get() = super.jsonWebKey.copy(algorithm = JweAlgorithm.ECDH_ES)
```

### Ad. 2

This can also be adjusted from consuming side, but shouldn't both values be derived from the issuer metadata?

```kotlin
WalletEncryptionService(supportedJweEncryptionAlgorithm = JweEncryption.A128GCM, ...)
```

**Comment by nodh** [comment]
Thank you so much for testing our implementation and reporting that bug!

I've fixed both issues in #464 -- what do you think about that?

**Comment by jonas-youniqx** [comment]
The changes look valid, thanks for the fast reaction. ~~I gave it a quick run and built the branch locally and still get the same error~~

~~I have to dig deeper and debug the root cause, not sure if I find the time this year.~~

edit: There seems to be an issue with taking the local version.

edit 2: Works like a charm 👏  tyvm.
